name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Apktool
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool

      - name: Build APK (Fast Mode)
        run: |
          # خيار -r يمنع إعادة بناء الموارد ويتجاوز أخطاء XML
          apktool b -r Source -o BEN10_Fixed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Final-Modded-APK
          path: BEN10_Fixed.apk
